### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by COD3BREAK3R** [nexes/statusbar-error#10] opened 2021-01-25 20:12 UTC
Please fix the extension, not working in VS Code 1.52.1, thanks for create this extension

**Comment by nexes** [comment] 2021-02-28 17:51
I cannot reproduce this issue. The current version of the extension is working for 1.52 and 1.53. No logs or crash report was given, closing issue.

**Closed as completed by nexes** 2021-02-28 17:51 UTC
